;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attribute.Health",DevComment="")
+GameplayTagList=(Tag="Buildable.Door",DevComment="")
+GameplayTagList=(Tag="Buildable.Door.Stone",DevComment="")
+GameplayTagList=(Tag="Buildable.Door.Wood",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Stone",DevComment="")
+GameplayTagList=(Tag="Buildable.Wall.Wood",DevComment="")
+GameplayTagList=(Tag="Resource",DevComment="")

